server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://www.liuhl.site/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 82515121zZ
  redis:
    host: www.liuhl.site
  rabbitmq:
    host: www.liuhl.site
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo